### PR TITLE
Fix Spark for Windows (fixes #265)

### LINKED ISSUE #265: Spark benchmarks fail on Windows
```
java.lang.Exception: Wrong winutils.exe size: expected 109568, written 112640
        at org.renaissance.apache.spark.SparkUtil.setUpHadoop(SparkUtil.scala:124)
        at org.renaissance.apache.spark.SparkUtil.setUpSparkContext(SparkUtil.scala:42)
        at org.renaissance.apache.spark.SparkUtil.setUpSparkContext$(SparkUtil.scala:38)
        at org.renaissance.apache.spark.Als.setUpSparkContext(Als.scala:50)
        at org.renaissance.apache.spark.Als.setUpBeforeAll(Als.scala:95)
        at org.renaissance.harness.ExecutionDriver.executeBenchmark(ExecutionDriver.java:59)
        at org.renaissance.harness.RenaissanceSuite$.$anonfun$runBenchmarks$1(RenaissanceSuite.scala:133)
        at org.renaissance.harness.RenaissanceSuite$.$anonfun$runBenchmarks$1$adapted(RenaissanceSuite.scala:127)
        at scala.collection.immutable.List.foreach(List.scala:333)
        at org.renaissance.harness.RenaissanceSuite$.runBenchmarks(RenaissanceSuite.scala:127)
        at org.renaissance.harness.RenaissanceSuite$.main(RenaissanceSuite.scala:104)
        at org.renaissance.harness.RenaissanceSuite.main(RenaissanceSuite.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.renaissance.core.Launcher.loadAndInvokeHarnessClass(Launcher.java:114)
        at org.renaissance.core.Launcher.launchHarnessClass(Launcher.java:73)
        at org.renaissance.core.Launcher.main(Launcher.java:37)
```

Probably due to update of `winutils.exe` resource.

### PR DESCRIPTION
**Pull request by vhotspur**
Basically only added one extra DLL that is required for native operations.

The DLL must be explicitly loaded as otherwise it is not found (setting only `hadoop.home.dir` is not enough; setting `java.library.path` should work but it is done probably too late to have any effect).

### CODE REVIEW

File: benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/SparkUtil.scala [hunk 1]
```diff
@@ -98,6 +107,29 @@ trait SparkUtil {
     sparkSession.close()
   }
 
+  private def copyResourceToDir(
```
Comment (lbulej) [inline benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/SparkUtil.scala:110]: I would suggest to put this function into `ResourceUtil`.

**Review by lbulej — APPROVED** [review]
LGTM

File: benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/SparkUtil.scala (hunk 1 above)
Comment (vhotspur) [reply benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/SparkUtil.scala]: Done.
