### PR TITLE
Address RDD caching problems

### LINKED ISSUE #226: log-regression benchmark doesn't cache its RDD
All Spark benchmarks are structured the same way and start by loading data from files, then transform it in an RDD and then run the benchmark on the cached RDD.
However, the `log-regression` benchmark doesn't cache its RDD, recomputing it during the iteration of the benchmarks. This is an inconsistency and a problem we have to fix.

Credit goes to @tkrodriguez for spotting the issue.

```
diff --git a/benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/LogRegression.scala b/benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/LogRegression.scala
index ee5daad..0fefa91 100644
--- a/benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/LogRegression.scala
+++ b/benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/LogRegression.scala
@@ -96,7 +96,7 @@ final class LogRegression extends Benchmark with SparkUtil {
           features(index) = value
         }
         (parts(0).toDouble, Vectors.dense(features))
-      }
+      }.cache();
   }
 
   override def setUpBeforeAll(c: BenchmarkContext): Unit = {
```

### PR DESCRIPTION
**Pull request by farquet**
This fixes #226 .
Moreover, since we don't really have unit tests, I've added a `checkCaching` method to the `SparkUtil` trait. That way we can explicitly mark some RDDs that need to be cached and fail otherwise. That will make things explicit and avoid such problems in the future.
Before I start porting this extra check to all Spark benchmarks that use RDDs, please let me know if you think this idea makes sense (or if you see a better way to achieve the same thing).

### CODE REVIEW

File: benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/SparkUtil.scala [hunk 1]
```diff
@@ -59,4 +61,10 @@ trait SparkUtil {
       System.setProperty("hadoop.home.dir", tempDirPath.toAbsolutePath.toString)
     }
   }
+
+  def checkCaching[T](rdd: RDD[T]): Unit = {
+    if (!rdd.getStorageLevel.useMemory) {
```
Comment (farquet) [inline benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/SparkUtil.scala:66]: `rdd.getStorageLevel.useMemory` is true when `cache()` has been called on the RDD.

**Comment by davleopo** [comment]
LGTM, seems to do the trick

**Comment by lbulej** [comment]
LGTM.

File: benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/DecTree.scala [hunk 2]
```diff
@@ -118,7 +118,7 @@ final class DecTree extends Benchmark with SparkUtil {
 
     tempDirPath = c.generateTempDir("dec_tree")
     sc = setUpSparkContext(tempDirPath, threadCountParam, "dec-tree")
-    training = prepareAndLoadInput(decisionTreePath, inputFile)
+    training = prepareAndLoadInput(decisionTreePath, inputFile).cache()
```
Comment (lbulej) [inline benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/DecTree.scala:121]: Good catch, I was only searching for RDD type.

**Comment by farquet** [comment]
The `dec-tree` benchmark contains a spark SQL DataFrame set to `sqlContext.read.format("libsvm").load(bigInputFile.toString)`.
This is also lazy evaluated and not cached, so adding a `.cache()` at the that end of that line reduces the iteration time by ~30% (similarly on different JDKs tested).

Unfortunately, I can't find a way to check if a DataFrame is cached in the Spark documentation. So I can't have an `ensureCaching` method that takes a DataFrame as input.

**Comment by farquet** [comment]
Also addresses #227 now. `movie-lens` had quite some setup (or missing caches) happening in the core of the iteration. This reduces the iteration time by 15-20% which are taken from the initial bits of the execution, the rest (als algo training) is untouched.

**Comment by farquet** [comment]
I wonder why there is no Travis check running on this branch ?
I guess no check means no problem ! Merging.

**Comment by lbulej** [comment]
> I wonder why there is no Travis check running on this branch ?

I wonder too! I realized that Travis did not run for my earlier PR too...

**Comment by vhotspur** [comment]
> I wonder why there is no Travis check running on this branch ?
> I guess no check means no problem ! Merging.

The checks were running: https://travis-ci.org/github/renaissance-benchmarks/renaissance/pull_requests

But their status was not reported back... Might be related to https://www.traviscistatus.com/incidents/3krnmsdpp3t0
